version: '3.8'

services:
  # Application Service
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:testpass@postgres:5432/fanzmoneydash_test
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=test-jwt-secret-key
      - API_KEY_SECRET=test-api-key-secret
      - ENCRYPTION_KEY=test-encryption-key-32-bytes-long
      - HMAC_SECRET=test-hmac-secret
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=fanzmoneydash_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Load Testing
  k6:
    image: grafana/k6:latest
    volumes:
      - ./tests/performance:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: run --vus 50 --duration 5m /scripts/load-test.js
    depends_on:
      - app
      - influxdb

  # Metrics Collection
  influxdb:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6
    ports:
      - "8086:8086"
    volumes:
      - influxdb_test_data:/var/lib/influxdb

  # Metrics Visualization
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=testpass
    ports:
      - "3001:3000"
    volumes:
      - grafana_test_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb

volumes:
  postgres_test_data:
  redis_test_data:
  influxdb_test_data:
  grafana_test_data:

networks:
  default:
    driver: bridge